name: Deploy master
on:
push:
branches: [ master ]
jobs:
build:
runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v2
  - name: Set up JDK 11
uses: actions/setup-java@v2
with:
java-version: '11'
distribution: 'adopt'
cache: maven
  - name: Cache Maven packages
uses: actions/cache@v2
with:
path: ~/.m2
key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
restore-keys: ${{ runner.os }}-m2
  - name: Build with Maven
run: mvn -Dmaven.test.skip=true -B package --file pom.xml
  - name: Make Directory for deliver
run: mkdir deploy && cp target/*.jar deploy/ && cp appspec.yml deploy/ && cp script/deploy.sh deploy/
  - name: Make zip file
run: zip -r -qq -j jarZipFile.zip deploy
  - name: AWS credentials
uses: aws-actions/configure-aws-credentials@v1
with:
aws-access-key-id: ${{ secrets.DEV_AWS_ACCESS_KEY_DEPLOY }}
aws-secret-access-key: ${{ secrets.DEV_AWS_SECRET_KEY_DEPLOY }}
aws-region: ap-northeast-2
  - name: Upload to AWS S3
run: aws s3 cp --region ap-northeast-2 jarZipFile.zip s3://everyone-s-delivery/deploy/master/jarZipFile.zip
  - name: Code Deploy
run: aws deploy create-deployment --application-name everyone-s-delivery-deploy --deployment-config-name CodeDeployDefault.AllAtOnce --deployment-group-name eveyone-s-delivery-delpoy-group --s3-location bucket=everyone-s-delivery,bundleType=zip,key=deploy/master/jarZipFile.zip